server:
  port: 8080
  address: 0.0.0.0
spring:
  datasource:
    #    url: jdbc:h2:file:${H2_DIR:./data}/retrospect
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/${POSTGRES_DB:mfaserver}
    driverClassName: org.postgresql.Driver
    username: ${POSTGRES_USER:mfaserver}
    password: ${POSTGRES_PASSWORD:mfaserver}
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    properties:
      org.hibernate.flushMode: ALWAYS
  session:
    jdbc:
      initialize-schema: always
      schema: classpath:org/springframework/session/jdbc/schema-postgresql.sql
      table-name: SPRING_SESSION
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
#logging:
#  level:
#    org:
#      springframework:
#        security: TRACE

