server:
  port: 8080
  address: 0.0.0.0
spring:
  datasource:
#    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/${POSTGRES_DB:mfaserver}
#    driverClassName: org.postgresql.Driver
    url: jdbc:h2:mem:mfaserver}
    driverClassName: org.h2.Driver
    username: ${DB_USER:mfaserver}
    password: ${DB:mfaserver}
  jpa:
    show-sql: true
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    properties:
      org.hibernate.flushMode: ALWAYS
  session:
    jdbc:
      initialize-schema: always
      schema: classpath:org/springframework/session/jdbc/schema-h2.sql
      table-name: SPRING_SESSION
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
logging:
  level:
    org:
      springframework:
        security: DEBUG   '
application:
  nps-api-key: ${NPS_API_KEY}


